export {
  CancelParcelDocument as CANCEL_PARCEL,
  GetParcelImportDocument as GET_PARCEL_IMPORT,
  GetParcelImportsDocument as GET_PARCEL_IMPORTS,
  GetParcelDocument as PARCEL,
  GetPreLoadParcelsDocument as PRELOAD_PARCELS,
  GetParcelsForRouteCreationDocument as PARCELS_FOR_ROUTE,
  RegisterParcelDocument as REGISTER_PARCEL,
  GetRegisteredParcelsDocument as REGISTERED_PARCELS,
  UpdateParcelDocument as UPDATE_PARCEL,
} from "./generated";
export type {
  CancelParcelMutation,
  CancelParcelMutationVariables,
  GetParcelImportQuery,
  GetParcelImportQueryVariables,
  GetParcelImportsQuery,
  GetParcelImportsQueryVariables,
  GetParcelQuery,
  GetParcelQueryVariables,
  GetPreLoadParcelsQuery,
  GetPreLoadParcelsQueryVariables,
  GetParcelsForRouteCreationQuery,
  GetParcelsForRouteCreationQueryVariables,
  GetRegisteredParcelsQuery,
  GetRegisteredParcelsQueryVariables,
  RegisterParcelMutation,
  RegisterParcelMutationVariables,
  UpdateParcelMutation,
  UpdateParcelMutationVariables,
} from "./generated";
